<div
    hx-trigger="load"
    hx-target="this"
    hx-swap="outerHTML"
    hx-get="/cxn/{{$cxn->idConstruction}}/relations/formNew"
></div>
<div
    hx-trigger="load"
    hx-target="this"
    hx-swap="outerHTML"
    hx-get="/cxn/{{$cxn->idConstruction}}/relations/grid"
></div>
