<div
    hx-trigger="load"
    hx-target="this"
    hx-swap="outerHTML"
    hx-get="/microframe/{{$frame->idFrame}}/relations/formNew"
></div>
<div
    hx-trigger="load"
    hx-target="this"
    hx-swap="outerHTML"
    hx-get="/microframe/{{$frame->idFrame}}/relations/grid"
></div>
