<div
    hx-trigger="load"
    hx-target="this"
    hx-swap="outerHTML"
    hx-get="/layertype/{{$idLayerType}}/genericlabels/formNew"
></div>
<div
    hx-trigger="load"
    hx-target="this"
    hx-swap="outerHTML"
    hx-get="/layertype/{{$idLayerType}}/genericlabels/grid"
></div>
