<?php

namespace App\Console\Commands\FN3;

use App\Database\Criteria;
use Exception;
use Illuminate\Console\Command;

class CreateMissingLemmasCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'fn3:create-missing-lemmas
                            {--csv= : Path to CSV file (default: missing_lemmas.csv in Data directory)}
                            {--dry-run : Preview changes without writing to database}
                            {--user=6 : User ID for lemma creation}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create missing lemmas from the missing_lemmas.csv file generated by fn3:create-lus-from-csv';

    private array $stats = [
        'total_rows' => 0,
        'created' => 0,
        'skipped' => 0,
        'errors' => 0,
    ];

    private array $errorDetails = [];

    private array $skippedDetails = [];

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $this->info('Create Missing Lemmas from CSV');
        $this->newLine();

        // Configuration
        $csvPath = $this->option('csv') ?? __DIR__.'/Data/missing_lemmas.csv';
        $isDryRun = $this->option('dry-run');
        $userId = (int) $this->option('user');

        // Validate CSV file exists
        if (! file_exists($csvPath)) {
            $this->error("CSV file not found: {$csvPath}");

            return 1;
        }

        $this->info('Configuration:');
        $this->line("  - CSV File: {$csvPath}");
        $this->line("  - User ID: {$userId}");
        if ($isDryRun) {
            $this->warn('  - DRY RUN MODE - No database changes will be made');
        }
        $this->newLine();

        // Read CSV
        $this->info('Reading CSV file...');
        $rows = $this->readCsv($csvPath);

        if (empty($rows)) {
            $this->error('No data rows found in CSV file');

            return 1;
        }

        $this->stats['total_rows'] = count($rows);
        $this->info("Found {$this->formatNumber($this->stats['total_rows'])} rows to process");
        $this->newLine();

        // Process lemmas
        $this->info('Creating lemmas...');
        $this->newLine();

        $this->withProgressBar($rows, function ($row) use ($isDryRun, $userId) {
            $this->createLemma($row, $isDryRun, $userId);
        });

        $this->newLine(2);

        // Display statistics
        $this->displayStatistics($isDryRun);

        if ($this->stats['errors'] > 0) {
            $this->newLine();
            $this->displayErrorDetails();
        }

        if ($this->stats['skipped'] > 0) {
            $this->newLine();
            $this->displaySkippedDetails();
        }

        if ($isDryRun) {
            $this->newLine();
            $this->info('Dry run completed. Use without --dry-run to create lemmas.');
        } else {
            $this->newLine();
            $this->info('Lemma creation completed!');
        }

        return 0;
    }

    private function readCsv(string $csvPath): array
    {
        $rows = [];
        $handle = fopen($csvPath, 'r');

        if (! $handle) {
            $this->error('Failed to open CSV file');

            return [];
        }

        // Read header row to get column indices
        $header = fgetcsv($handle);
        $columns = array_flip($header);

        $lineNumber = 2;

        // Read data rows
        while (($data = fgetcsv($handle)) !== false) {
            if (count($data) >= 5) {
                $rows[] = [
                    'line_number' => $lineNumber,
                    'lemmaNamePt' => trim($data[$columns['lemmaName(pt)']] ?? ''),
                    'idUDPOS' => (int) trim($data[$columns['idUDPOS']] ?? 0),
                    'udPOS' => trim($data[$columns['udPOS']] ?? ''),
                ];
            }
            $lineNumber++;
        }

        fclose($handle);

        return $rows;
    }

    private function createLemma(array $row, bool $isDryRun, int $userId): void
    {
        $lemmaName = $row['lemmaNamePt'];
        $idUDPOS = $row['idUDPOS'];

        // Validate required fields
        if (empty($lemmaName) || $idUDPOS <= 0) {
            $this->stats['errors']++;
            $this->errorDetails[] = [
                'line' => $row['line_number'],
                'lemmaName' => $lemmaName,
                'error' => 'Missing required fields (lemmaName or idUDPOS)',
            ];

            return;
        }

        // Check if lemma already exists
        $exists = Criteria::table('view_lemma')
            ->where('name', $lemmaName)
            ->where('idUDPOS', $idUDPOS)
            ->where('idLanguage', 1)
            ->first();

        if ($exists) {
            $this->stats['skipped']++;
            $this->skippedDetails[] = [
                'line' => $row['line_number'],
                'lemmaName' => $lemmaName,
                'udPOS' => $row['udPOS'],
                'reason' => 'Lemma already exists',
            ];

            return;
        }

        // Build lemma data for lemma_create function
        $lemmaData = json_encode([
            'name' => $lemmaName,
            'idLanguage' => 1,
            'idUDPOS' => $idUDPOS,
            'idUser' => $userId,
        ]);

        try {
            if (! $isDryRun) {
                $idLemma = Criteria::function('lemma_create(?)', [$lemmaData]);

                // Handle Multi-Word Expressions (MWE)
                //                $isMWE = str_contains($lemmaName, ' ');
                //                if ($isMWE) {
                //                    $expressions = explode(' ', $lemmaName);
                //                    foreach ($expressions as $i => $expression) {
                //                        $exp = json_encode([
                //                            'form' => trim($expression),
                //                            'idLexiconGroup' => 1,
                //                        ]);
                //                        $idLexicon = Criteria::function('lexicon_create(?)', [$exp]);
                //                        Criteria::create('lexicon_expression', [
                //                            'idLemma' => $idLemma,
                //                            'idExpression' => $idLexicon,
                //                            'position' => $i,
                //                            'breakBefore' => 1,
                //                            'head' => $i === 0 ? 1 : 0,
                //                        ]);
                //                    }
                //                }
            }
            $this->stats['created']++;
        } catch (Exception $e) {
            $this->stats['errors']++;
            $this->errorDetails[] = [
                'line' => $row['line_number'],
                'lemmaName' => $lemmaName,
                'error' => $e->getMessage(),
            ];
        }
    }

    private function displayStatistics(bool $isDryRun): void
    {
        $this->info('Lemma Creation Results:');
        $this->newLine();

        $suffix = $isDryRun ? ' (would be)' : '';

        $tableData = [
            ['Total rows in CSV', $this->formatNumber($this->stats['total_rows'])],
            ['Lemmas created'.$suffix, $this->formatNumber($this->stats['created'])],
            ['Skipped (already exist)', $this->formatNumber($this->stats['skipped'])],
            ['Errors', $this->formatNumber($this->stats['errors'])],
        ];

        $this->table(['Metric', 'Count'], $tableData);
    }

    private function displayErrorDetails(): void
    {
        if (empty($this->errorDetails)) {
            return;
        }

        $this->error('Error Details (first 10):');
        $this->newLine();

        $sample = array_slice($this->errorDetails, 0, 10);
        $tableData = [];

        foreach ($sample as $error) {
            $tableData[] = [
                $error['line'],
                $error['lemmaName'],
                substr($error['error'], 0, 60).(strlen($error['error']) > 60 ? '...' : ''),
            ];
        }

        $this->table(['CSV Line', 'Lemma', 'Error'], $tableData);

        if (count($this->errorDetails) > 10) {
            $this->line('  ... and '.(count($this->errorDetails) - 10).' more errors');
        }
    }

    private function displaySkippedDetails(): void
    {
        if (empty($this->skippedDetails)) {
            return;
        }

        $this->warn('Skipped Details (first 10):');
        $this->newLine();

        $sample = array_slice($this->skippedDetails, 0, 10);
        $tableData = [];

        foreach ($sample as $skipped) {
            $tableData[] = [
                $skipped['line'],
                $skipped['lemmaName'],
                $skipped['udPOS'],
                $skipped['reason'],
            ];
        }

        $this->table(['CSV Line', 'Lemma', 'POS', 'Reason'], $tableData);

        if (count($this->skippedDetails) > 10) {
            $this->line('  ... and '.(count($this->skippedDetails) - 10).' more skipped');
        }
    }

    private function formatNumber(int $number): string
    {
        return number_format($number);
    }
}
