<div
    hx-trigger="load"
    hx-target="this"
    hx-swap="outerHTML"
    hx-get="/ce/{{$idConstructionElement}}/constraints/formNew"
></div>
<div
    hx-trigger="load"
    hx-target="this"
    hx-swap="outerHTML"
    hx-get="/ce/{{$idConstructionElement}}/constraints/grid"
></div>
