<div
    hx-trigger="load"
    hx-target="this"
    hx-swap="outerHTML"
    hx-get="/fe/{{$idFrameElement}}/constraints/formNew"
></div>
<div
    hx-trigger="load"
    hx-target="this"
    hx-swap="outerHTML"
    hx-get="/fe/{{$idFrameElement}}/constraints/grid"
></div>
