@php
    $currentObject = null;
@endphp
<div x-data="timelineComponent({
            idDocument: {{$idDocument}},
            annotationType: '{{$annotationType}}',
            minFrame: {{$timeline['config']['minFrame']}},
            maxFrame: {{$timeline['config']['maxFrame']}},
            frameToPixel: {{$timeline['config']['frameToPixel']}},
            labelWidth: {{$timeline['config']['labelWidth']}}
    })" class="timeline"
    @timeline-seek-frame.document="onSeekObject"
>
    <div class="container">
        <!-- Controls -->
        <div class="controls ui form">
                <label>Go to frame:</label>
            <div class="ui small input">
                <input
                    type="number"
                    id="frame-input"
                    value="0"
                    min="0"
                    max="{{$timeline['config']['maxFrame']}}"
                    x-model="frameInput"
                    @keydown.enter="scrollToFrame()"
                >
            </div>
            <button class="ui small button" @click="scrollToFrame()">Go</button>
            <button class="ui small button" @click="scrollToStart()">Start</button>
            <button class="ui small button" @click="scrollToEnd()">End</button>
            <button class="ui small button" @click="scrollToVideoFrame()">same as Video</button>
            <span class="invisible" id="current-frame">Frame: 0</span>
        </div>

        <!-- Ruler -->
        <div class="ruler">
            <div class="label-area">
                Layers
            </div>
            <div class="content-area">
                <div class="content" id="ruler-content">
                    <!-- Ruler ticks will be generated by JavaScript -->
                </div>
            </div>
        </div>

        <!-- Main content area -->
        <div class="main">
            <!-- Labels column -->
            <div class="labels-column" id="labels-column">
                @foreach ($groupedLayers as $visualLayer)
                    @php $layerHeight = count($visualLayer['lines']) * $timeline['config']['objectHeight']; @endphp
                    <div class="label-item" style="height: {{ $layerHeight }}px;">
                        {{ $visualLayer['name'] }}
                    </div>
                @endforeach
            </div>
            <!-- Timeline content -->
            <div class="content" id="timeline-content" style="">
                <div class="inner" style="width: {{ $timeline['config']['timelineWidth'] }}px;">
                    @foreach ($groupedLayers as $visualLayerIndex => $visualLayer)
                        @php
                            $layerHeight = count($visualLayer['lines']) * $timeline['config']['objectHeight'];
                        @endphp
                        <div class="layer-row" style="height: {{ $layerHeight }}px;">
                            <!-- Layer Objects -->
                            <div
                                class="objects"
                                style="height: {{ $layerHeight }}px;"
{{--                                hx-get="/annotation/video/object"--}}
{{--                                hx-target="#formsPane"--}}
{{--                                hx-swap="innerHTML"--}}
{{--                                hx-on::config-request="event.detail.parameters.append('idObject', event.detail.triggeringEvent.target.dataset.id);event.detail.parameters.append('annotationType', '{{$annotationType}}')"--}}
                            >
                                @foreach ($visualLayer['lines'] as $lineIndex => $line)
                                    @foreach ($line['objects'] as $objIndex => $objectData)
                                        @php
                                            $startPos = ($objectData->startFrame - $timeline['config']['minFrame']) * $timeline['config']['frameToPixel'];
                                            $duration = $objectData->endFrame - $objectData->startFrame;
                                            $width = max($timeline['config']['minObjectWidth'], $duration * $timeline['config']['frameToPixel']);
                                            $top = $lineIndex * $timeline['config']['objectHeight'];
                                            if ($objectData->idObject == $idObject) {
                                                $currentObject = $objectData;
                                            }
                                        @endphp
                                        <div
                                            class="object"
                                            style="left: {{ $startPos }}px; top: {{ $top }}px; width: {{ $width }}px;"
                                            data-layer-index="{{ $line['originalIndex'] }}"
                                            data-object-index="{{ $objIndex }}"
                                            data-line-index="{{ $lineIndex }}"
                                            data-start-frame="{{ $objectData->startFrame }}"
                                            data-end-frame="{{ $objectData->endFrame }}"
                                        >
                                            @include("Annotation.Video.Panes.timeline.object")
                                        </div>
                                    @endforeach
                                @endforeach
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>

        <!-- Info bar -->
        <div class="info" id="timeline-info">
            Timeline ready - scroll to navigate
        </div>
    </div>
</div>

<!-- Dynamic Content Areas -->
<div id="highlight-container"></div>
<div id="object-click-info"></div>

@if($currentObject)
<script type="text/javascript">
    $(function() {
        document.dispatchEvent(new CustomEvent("timeline-seek-frame", { detail: { frameNumber: {{$currentObject->startFrame}} } }));
    });
</script>
@endif
