<div
    hx-trigger="load"
    hx-target="this"
    hx-swap="outerHTML"
    hx-get="/lemma/{{$lemma->idLemma}}/expressionsForm"
></div>
<div
    hx-trigger="load"
    hx-target="this"
    hx-swap="outerHTML"
    hx-get="/lemma/{{$lemma->idLemma}}/expressionsGrid"
></div>
