<div
    hx-trigger="load"
    hx-target="this"
    hx-swap="outerHTML"
    hx-get="/lemma/{{$lemma->idLemma}}/posForm"
></div>
<div
    hx-trigger="load"
    hx-target="this"
    hx-swap="outerHTML"
    hx-get="/lemma/{{$lemma->idLemma}}/posGrid"
></div>
