<div
    hx-trigger="load"
    hx-target="this"
    hx-swap="outerHTML"
    hx-get="/domain/{{$idDomain}}/semanticTypes/formNew"
></div>
<div
    hx-trigger="load"
    hx-target="this"
    hx-swap="outerHTML"
    hx-get="/domain/{{$idDomain}}/semanticTypes/grid"
></div>
